name: Monoflow - Feature Env
on:
  push:
    branches:
      - '!development'
      - 'main'
      - '*feature*'

env:
  REPOSITORY_NAME: identity-suite
  AWS_DEFAULT_REGION: us-east-1
  AWS_DEFAULT_OUTPUT: json

jobs:

  run-master-workflow:
    uses: wechorg/reusablebug/.github/workflows/master-workflow.yml@development
    with:
      repo_name: identity-suite
      cluster_name: feature
